obf_metadata_config:
- name: attn_pi
  shape: [3584, ]
  type: rearrange
  save_metadata: True
- name: attn_kv_pi
  shape: [512, ]
  type: rearrange
  save_metadata: False
- name: attn_pi_inv
  shape: [3584, ]
  type: rearrange
  save_metadata: True
- name: attn_kv_pi_inv
  shape: [512, ]
  type: rearrange
  save_metadata: False
- name: mlp_pi
  shape: [18944, ]
  type: rearrange
  save_metadata: False
- name: alpha_q
  shape: [1, ]
  type: random
  save_metadata: False
- name: alpha_k
  shape: [1, ]
  type: random
  save_metadata: False
weight_obf_config:
- target: model/layers/${layer}/input_layernorm/weight
  layers: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]
  weight_obf_ops:
  - name: permuate
    input_x: weight
    input_y: attn_pi
    axis: 0
- target: model/layers/${layer}/post_attention_layernorm/weight
  layers: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]
  weight_obf_ops:
  - name: permuate
    input_x: weight
    input_y: attn_pi
    axis: 0
- target: model/layers/${layer}/self_attn/k_proj/weight
  layers: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]
  weight_obf_ops:
  - name: permuate
    input_x: weight
    input_y: attn_pi
    axis: 1
  - name: mul
    input_x: weight
    input_y: alpha_k
- target: model/layers/${layer}/self_attn/k_proj/bias
  layers: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]
  weight_obf_ops:
  - name: mul
    input_x: weight
    input_y: alpha_k
- target: model/layers/${layer}/self_attn/v_proj/weight
  layers: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]
  weight_obf_ops:
  - name: permuate
    input_x: weight
    input_y: attn_kv_pi
    axis: 0
  - name: permuate
    input_x: weight
    input_y: attn_pi
    axis: 1
- target: model/layers/${layer}/self_attn/v_proj/bias
  layers: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]
  weight_obf_ops:
  - name: permuate
    input_x: bias
    input_y: attn_kv_pi
    axis: 0
- target: model/layers/${layer}/self_attn/q_proj/weight
  layers: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]
  weight_obf_ops:
  - name: permuate
    input_x: weight
    input_y: attn_pi
    axis: 1
  - name: mul
    input_x: weight
    input_y: alpha_q
- target: model/layers/${layer}/self_attn/q_proj/bias
  layers: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]
  weight_obf_ops:
  - name: mul
    input_x: weight
    input_y: alpha_q
- target: model/layers/${layer}/self_attn/o_proj/weight
  layers: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]
  weight_obf_ops:
  - name: permuate
    input_x: weight
    input_y: attn_pi
    axis: 0
  - name: permuate
    input_x: weight
    input_y: attn_pi
    axis: 1
- target: model/layers/${layer}/mlp/down_proj/weight
  layers: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]
  weight_obf_ops:
  - name: permuate
    input_x: weight
    input_y: attn_pi
    axis: 0
  - name: permuate
    input_x: weight
    input_y: mlp_pi
    axis: 1
- target: model/layers/${layer}/mlp/gate_proj/weight
  layers: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]
  weight_obf_ops:
  - name: permuate
    input_x: weight
    input_y: mlp_pi
    axis: 0
  - name: permuate
    input_x: weight
    input_y: attn_pi
    axis: 1
- target: model/layers/${layer}/mlp/up_proj/weight
  layers: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]
  weight_obf_ops:
  - name: permuate
    input_x: weight
    input_y: mlp_pi
    axis: 0
  - name: permuate
    input_x: weight
    input_y: attn_pi
    axis: 1